server:
  port: 18080

#spring:
#  mvc:
#    view:
#      prefix: /WEB-INF/jsp/ # Read From Web Resources Dir
#      suffix: .jsp

#配置数据源
#spring:
#  datasource:
#    url: jdbc:mysql://mysql.dev.idc.cedu.cn:3306/qq_virtual_property?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
#    username: qingqingDev
#    password: qingqing@dev
#    driver-class-name: com.mysql.jdbc.Driver
